// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Database;

namespace Notification.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Notification.Model.NotificationQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedTimestamp");

                    b.Property<DateTime?>("ExpiredTimestamp");

                    b.Property<short>("FailCount");

                    b.Property<DateTime?>("FirstAttemptedTimestamp");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime?>("LastAttemptedTimestamp");

                    b.Property<DateTime?>("SentTimestamp");

                    b.Property<string>("Subject")
                        .HasMaxLength(300);

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("NotificationQueues");

                    b.HasData(
                        new { Id = 1, Body = "This is content of the <b>Email</b> message", CreatedTimestamp = new DateTime(2018, 11, 18, 12, 32, 30, 917, DateTimeKind.Local), FailCount = (short)0, From = "notification.test@com", Subject = "Test email notification", To = "avdohusic@gmail.com" },
                        new { Id = 2, Body = "This is content of the <b>Email</b> message", CreatedTimestamp = new DateTime(2018, 11, 18, 12, 32, 30, 919, DateTimeKind.Local), FailCount = (short)0, From = "notification.test@com", Subject = "Test email notification", To = "avdo.husic@gmail.com" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
